export const COUNTRIES = [
  "Albania",
  "Algeria",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Bolivia",
  "Bosnia",
  "Brazil",
  "Cambodia",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Honduras",
  "Hungary",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Lebanon",
  "Libya",
  "Malaysia",
  "Mexico",
  "Netherlands",
  "Morocco",
  "Moldova",
  "Montenegro",
  "Myanmar",
  "Nepal",
  "New Zealand",
  "Nicaragua",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Rwanda",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Tanzania",
  "Thailand",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vietnam",
] as const;

export const VISA_TYPES = [
  "Tourist",
  "Digital Nomad",
  "Golden Visa / Investor",
  "Student",
  "Work Permit",
  "Skilled Worker (EU Blue Card, etc.)",
  "Retirement / Passive Income (D7, etc.)",
  "Family Reunification",
  "Freelancer Visa",
  "Startup / Entrepreneur Visa",
  "Refugee / Asylum",
  "Long-term Residence",
  "Citizenship by Investment",
  "Other",
] as const;

export const INCOME_RANGES = [
  "Under $1k",
  "$1k-$3k",
  "$3k-$5k",
  "$5k-$10k",
  "$10k+",
] as const;

export const PROCESSING_TIMES = [
  "Under 1 month",
  "1-3 months",
  "3-6 months",
  "6+ months",
] as const;

export type ResultValue = "approved" | "rejected" | "pending";

export const RESULT_LABELS: Record<ResultValue, string> = {
  approved: "Approved",
  rejected: "Rejected",
  pending: "Pending",
};
