const FLAG_BY_COUNTRY: Record<string, string> = {
  "United States": "🇺🇸",
  "United Kingdom": "🇬🇧",
  Canada: "🇨🇦",
  Australia: "🇦🇺",
  Germany: "🇩🇪",
  France: "🇫🇷",
  Spain: "🇪🇸",
  Italy: "🇮🇹",
  Netherlands: "🇳🇱",
  Portugal: "🇵🇹",
  Ireland: "🇮🇪",
  Sweden: "🇸🇪",
  Norway: "🇳🇴",
  Switzerland: "🇨🇭",
  Japan: "🇯🇵",
  "South Korea": "🇰🇷",
  Singapore: "🇸🇬",
  "United Arab Emirates": "🇦🇪",
  "New Zealand": "🇳🇿",
  Mexico: "🇲🇽",
  Brazil: "🇧🇷",
  Argentina: "🇦🇷",
  India: "🇮🇳",
  China: "🇨🇳",
  Thailand: "🇹🇭",
  Vietnam: "🇻🇳",
  Indonesia: "🇮🇩",
  Malaysia: "🇲🇾",
  Philippines: "🇵🇭",
  "South Africa": "🇿🇦",
  Egypt: "🇪🇬",
  Turkey: "🇹🇷",
  Poland: "🇵🇱",
  "Czech Republic": "🇨🇿",
  Austria: "🇦🇹",
  Belgium: "🇧🇪",
  Greece: "🇬🇷",
  Croatia: "🇭🇷",
  Hungary: "🇭🇺",
  Romania: "🇷🇴",
  Denmark: "🇩🇰",
  Finland: "🇫🇮",
  Israel: "🇮🇱",
  "Saudi Arabia": "🇸🇦",
  Qatar: "🇶🇦",
  Colombia: "🇨🇴",
  Chile: "🇨🇱",
  Peru: "🇵🇪",
  Nigeria: "🇳🇬",
  Kenya: "🇰🇪",
};

export function flagForCountry(country: string): string {
  return FLAG_BY_COUNTRY[country] ?? "🌍";
}
